
name: Deployment

on:
  push:
    branches: master

jobs:
  #First we will see the application build or not , then we will deploy in EC2
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm i -f

      - name: Buid the application
        run: npm run build

  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Development
        if: github.ref == 'refs/heads/master'
        env:
          PRIVATE_KEY: ${{ secrets.NT_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.NT_DEV_HOSTNAME }}
          UNAME: ${{ secrets.UNAME }}
          PWD: ${{ secrets.PWD }}
        run: |
          /usr/bin/sshpass "${{ secrets.PWD }}"  ssh -o StrictHostKeyChecking=no sdcusr@${{secrets.UNAME}} '
      
            cd var/www/html/aim_be &&
            git checkout development &&
            git pull origin development &&
            npm i -f && NODE_OPTIONS="--max-old-space-size=1024" npm run build && npm run start:prod && pm2 save -f'

      
  
