name: Deployment

on:
  push:
    branches: master

jobs:
  #First we will see the application build or not , then we will deploy in EC2
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm i -f

      - name: Buid the application
        run: npm run build

  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to master
        if: github.ref == 'refs/heads/master'
        env:
          PRIVATE_KEY: ${{ secrets.NT_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.NT_DEV_HOSTNAME }}
        run: |
           echo "$PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
           ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${HOSTNAME} '
            cd /home/ubuntu/aim_be &&
            git checkout master &&
            git pull origin &&
            npm i -f && npm run build && npm run start:prod && pm2 save -f'
           


  
